services:
  - type: web
    name: botdiscord
    env: node
    buildCommand: npm install
    startCommand: npm start
services:
  - type: web
    name: botdiscord
    env: node
    buildCommand: npm install
    startCommand: npm start
